name: debug_output
description: debug_output project
version: 2025.504.1731
homepage: 
repository: https://github.com/dart-pkg/debug_output
environment:
  sdk: ^3.7.2
dependencies:
  text_serializer: ^2025.502.1757
dev_dependencies:
  test: ^1.26.2
  lints: ^6.0.0
