name: debug_output
description: debug_output project
version: 0.0.1
homepage: 
repository: https://github.com/dart-pkg/debug_output
environment:
  sdk: ^3.7.2
dependencies:
  text_serializer: ^2025.502.1757
dev_dependencies:
  test: ^1.25.15
  std: ^2025.501.843
  lints: ^5.1.1
